name: test_actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Run cmake --version
        shell: bash
        run: |
          VERSION=`cmake --version`
          echo $VERSION
      - name: install_test
        run: |
          pip install --user cpp-coveralls
      - name: build
        shell: bash
        run: |
          cmake CMakeLists.txt
          cmake --build
          ./configure --enable-gcov && make && make check
